version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo "Running lint..."
      - npm run lint
      - echo "Generating database migrations..."
      - npm run generate
  build:
    commands:
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  base-directory: '.'
  files:
    - '**/*'
  name: nextjs-full-project-artifact